### ISSUE TITLE
`islice` not stopping after end

### ISSUE THREAD

**Issue by Kareem-Medhat** [nvie/itertools#979]
Consider these examples:
```js
import { islice } from 'itertools';

function* positiveWholeNumbers() {
  let n = 1;
  while (true) {
    yield n++;
  }
}

const first5 = islice(positiveWholeNumbers(), 5);
console.log(Array.from(first5));
```

Expected behaviour: [1, 2, 3, 4, 5]
Current behaviour: Infinite loop

**Comment by nvie** [comment]
Eek, you're right, that's no good. I must have introduced a regression, will get this fixed ASAP.

**Comment by Kareem-Medhat** [comment]
I'm almost done finishing up a pull request and will reference this issue there

**Comment by nvie** [comment]
> I'm almost done finishing up a pull request and will reference this issue there

Oh sorry, @Kareem-Medhat – I only saw this message now. I've already opened a PR with a fix, see #980. Would you mind reviewing it? If okay, I'll release this as 2.2.1 later today.

**Comment by Kareem-Medhat** [comment]
no worries

**Comment by Kareem-Medhat** [comment]
done! commented on some minor stuff but other than that all looks good :+1:
